image: docker-reg.devops.xiaohongshu.com/fe/fe-ci:v3.8.5-6

before_script:
  - node -v

stages:
  - deps
  - test
  - deploy

deps:
  stage: deps
  script:
    - npm i -g pnpm@7
    - pnpm i

test:
  stage: test
  script:
    - npm run package
    - npm run test

deploy:production:
  stage: deploy
  script:
    - pnpm publish -r
  only:
    - /^v\d+\.\d+\.\d+$/

deploy:prerelease:
  stage: deploy
  script:
    - npm publish --tag=prerelease -r
  only:
    - /^v\d+\.\d+\.\d+-\d+$/
